### ISSUE TITLE
Missing blank README

### ISSUE THREAD

**Issue by kyle-github** [libplctag/goplctag#1]
I see that the default repo creation made a LICENSE file but not a README.   Even though I checked that box.

**Comment by TheFern2** [comment]
No worries, easy fix. I'll take care of this.

**Comment by kyle-github** [comment]
The original Go wrapper was licensed with both LGPL and MPL.  I did get an OK from the author when I changed the licensing of the C library from all the contributors.  So if we start with the original wrapper, we might need to use the dual license.   I think your plan of rapidly moving to a generated wrapper will mean any license would work but the dual license seems to make people pretty happy.

**Comment by TheFern2** [comment]
Dual license is fine with me. I'd still like to add the original wrapper to the repo for historical purposes.

**Comment by TheFern2** [comment]
Added both licenses to initial release.
