### ISSUE TITLE
Propose new repo name

### ISSUE THREAD

**Issue by TheFern2** [libplctag/goplctag#2]
Doing some thinking, if I structure the wrapper package inside a folder so that there could be other folders for examples, docs, etc in the repo root directory, the package import will look like this in a project used as dep:

```
import "github.com/libplctag/goplctag/goplctag"
```
I am thinking to change repo name to go, and then package name to plctag, then import will look like this, a bit cleaner:

```
import "github.com/libplctag/go/plctag"
```

**Comment by kyle-github** [comment]
Ah, the path is a bit duplicative.   Of course, the C library is like that github.com/libplctag/libplctag.  The C library is rarely pulled directly based on the URL though.

Does Go have any defaults it automatically adds to the URL?

**Comment by TheFern2** [comment]
You can have the entire module on the repo root directory but that will be a bit messy especially with auto-generated helper files or add the package folder. Without the folder the import becomes the github url as is. "import github.com/libplctag/goplctag" but if there's an explicit package directory then that needs to added to the url path "import github.com/libplctag/goplctag/goplctag". Packages are very much alike Java packages, say you had another package within this module called utils, then import would be "github.com/libplctag/goplctag/utils". Hopefully this answers the question.

**Comment by kyle-github** [comment]
Sorry busy with my day job today.   I can still change the repo name.  I think?   Not sure if GitHub makes that easy.

**Comment by TheFern2** [comment]
I think I can change it, I just wanted to make sure you were onboard with the change.

**Comment by kyle-github** [comment]
Sure.   There is not much of a pattern yet.
